apiVersion: v1
kind: Pod
metadata:
   name: mypod
spec:
  containers:
     - name: container1
       image: httpd:alpine
       resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 500Mi
