apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videos-app
  template:
    metadata:
      labels:
        app: videos-app
    spec:
      containers:
      - name: videos-app
        image: httpd:latest
        ports:
        - containerPort: 80