apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
   containers:
      - name: container1
        image: httpd:latest
        ports:
          - containerPort: 80

      - name: container2
        image: busybox:latest
        command: ["sleep","3600"]
