apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydem
  namespace: default
spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: nginx
          image: nginx:latest
