apiVersion: v1
kind: Pod
metadata:
   name: mypod
spec:
  containers:
      - name: maria
        image: mariadb:latest
        ports:
           - containerPort: 3306
        envFrom:
           - secretRef:
               name: mariasecret
